services:
  image_host_web:  # Название сервиса
    build:
      context: .  # Путь к Dockerfile
      dockerfile: Dockerfile  # Имя Dockerfile
    container_name: site-foto-web  # Имя контейнера
    restart: unless-stopped  # Перезапуск, если контейнер аварийно остановлен

    volumes:
      - images:/app/static/images  # том 'images' подключен к /app/static/images
      - logs:/app/logs             # том 'logs' подключен к /app/logs
    expose:
      - 8000  # Порта, которые будут доступны извне
    ports:
      - "8000:8000"  # Проброс порта

    networks:
      - default  # Подключение к сети

networks:
  default:  # Сеть по умолчанию
    driver: bridge  # Тип сети

volumes:
  images:  # Объявление именованного тома 'images'
  logs:    # Объявление именованного тома 'logs'
